name: Gateway Server Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - "gateway/**"
    - ".github/workflows/gateway.yaml"

jobs:
  gateway_server_cicd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/home_management_system/gateway:latest
        context: gateway/.
